### ISSUE TITLE
Implement partial vacuum states

### ISSUE THREAD

**Issue by KlimkinND** [jfeist/QuantumAlgebra.jl#22]
**Description**

Consider an operator A acting on multiple modes, e.g. $A[a, b]$. Suppose we need to compute its action on a state that's only a vacuum state for some modes, e.g. $\ket{\psi} = \ket{\phi_{a}} \otimes \ket{0_{b}}$ with no assumptions made for $\ket{\phi_{a}}$.

**Suggested solution**

Add an option to the `vacA` and `Avac` functions, respectively, which lets the user specify which particular modes are assumed to be in a vacuum state.

**Comment by jfeist** [comment]
Thanks for the suggestion, this has been implemented and released in v1.5.0.
