### ISSUE TITLE
Prettyprint powers of parameters

### ISSUE THREAD

**Issue by arnelg** [jfeist/QuantumAlgebra.jl#4]
This is a feature request to prettyprint powers of parameters and operators, e.g.
```
x = param(:x)
x * x
```
would display as $x^2$ instead of $x x$.

**Comment by jfeist** [comment]
Done (in the full_rewrite branch)! It was actually quite straightforward.
<img src="https://user-images.githubusercontent.com/2112929/125192698-806c4000-e249-11eb-9d79-6d0a38ddfdc0.png" width="500">
